export enum TodoistColor {
  BERRY_RED = 'berry_red',
  RED = 'red',
  ORANGE = 'orange',
  YELLOW = 'yellow',
  OLIVE_GREEN = 'olive_green',
  LIME_GREEN = 'lime_green',
  GREEN = 'green',
  MINT_GREEN = 'mint_green',
  TEAL = 'teal',
  SKY_BLUE = 'sky_blue',
  LIGHT_BLUE = 'light_blue',
  BLUE = 'blue',
  GRAPE = 'grape',
  VIOLET = 'violet',
  LAVENDER = 'lavender',
  MAGENTA = 'magenta',
  SALMON = 'salmon',
  CHARCOAL = 'charcoal',
  GREY = 'grey',
  TAUPE = 'taupe',
}

export enum TodoistColorCode {
  black = '#000000',
  red = '#db4035',
  berry_red = '#b8256f',
  green = '#299438',
  olive_green = '#afb83b',
  lime_green = '#7ecc49',
  mint_green = '#6accbc',
  teal = '#158fad',
  sky_blue = '#14aaf5',
  light_blue = '#96c3eb',
  blue = '#1fb6ff',
  purple = '#7e5bef',
  grape = '#884dff',
  violet = '#af38eb',
  lavender = '#eb96eb',
  pink = '#ff49db',
  magenta = '#e05194',
  salmon = '#ff8d85',
  charcoal = '#808080',
  grey = '#b8b8b8',
  taupe = '#ccac93',
  orange = '#ff9933',
  yellow = '#fad000',
}
